services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: dockerFile
    env_file:
      - .env
    # volumes:
    #   - ./app:/app
    #   - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - goods_deals
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: dockerFile
    # volumes:
    #   - ./api:/app
    #   - /api/node_modules
    ports:
      - 3001:3000
    env_file:
      - .env
    networks:
      - goods_deals
  db:
    container_name: db
    image: postgres:16
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - goods_deals

  adminer:
    container_name: adminer
    image: adminer
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - goods_deals

networks:
  goods_deals:
    driver: bridge
