FROM node:22-alpine

WORKDIR /usr/src/api

COPY package*.json ./

RUN npm install -g pnpm@latest

COPY . .

RUN pnpm install --frozen-lockfile

# RUN pnpm i ts-node
EXPOSE 3000

RUN pnpm add -D ts-node typescript

RUN pnpx prisma generate

CMD ["pnpm", "start"]